### ISSUE TITLE
Let user know if they are not running the most current version of the cli

### ISSUE THREAD

**Issue by mkinney** [meshtastic/python#274]
Let the user know if they are not running the most current version of the cli.

Use code like this https://github.com/meshtastic/Meshtastic-gui-installer/blob/master/meshtastic_flasher/util.py#L155

Perhaps, add a line at the bottom of the output on `--info` that would say something like:

```
Version: 1.2.3  *** There is a newer version. Consider running "pip install --upgrade meshtastic" ***
```

**Comment by luzpaz** [comment]
Ticket can be closed due to #434 being merged
