### ISSUE TITLE
Running `smokevirt` with a device plugged in fails

### ISSUE THREAD

**Issue by mkinney** [meshtastic/python#288]
It was successful with 1.2.57.f7c6955 , but not when a device is plugged in:

<img width="1030" alt="Screen Shot 2022-03-01 at 5 23 04 PM" src="https://user-images.githubusercontent.com/2219838/156277319-fc2c6dfc-7fed-4f28-aa1b-cae3acb5d2de.png">

**Comment by garthvh** [comment]
Stale
