### ISSUE TITLE
Cannot be export/import canned message

### ISSUE THREAD

**Issue by amerinoj** [meshtastic/python#324]
I don't nkow if don't implemented yet, but when you do a a export the canned messages are not exported and them the import don't have the option to upload the canned message via .yaml file.

**Comment by mkinney** [comment]
I have created https://github.com/meshtastic/Meshtastic-python/pull/325 but I am getting inconsistent results when I run the `set`. See https://github.com/meshtastic/Meshtastic-device/issues/1378

**Comment by garthvh** [comment]
Canned messages module config is part of the export but the string of message is still not

**Comment by amerinoj** [comment]
Ok rcarteraz, I'll closed the issue we Will follow in #426
