### ISSUE TITLE
notkia

### ISSUE THREAD

**Issue by xor256** [meshtastic/python#394]
Is possible move softweare to notkia? https://youtu.be/p9FBPlKkx5s?t=197

**Comment by sachaw** [comment]
https://dontasktoask.com/

**Comment by caveman99** [comment]
the phone runs mainline linux, so if python is availabe, the meshtastic python client can just be installed. Porting the Meshtastic firmware to the device will not happen anytime soon, this is a 'raspberry py alike' setup which is currently not supported.
