### ISSUE TITLE
[Bug]: Numbers ignored in BLE short name when configuring with config.yaml

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/python#397]
### Category

BLE

### Hardware

T-Beam

### Firmware Version

2.0.2.8146e84 Alpha

### Description

When configuring a device using a config.yaml file (e.g. meshtastic --configure config.yaml) all setting appear to be set as configured except for BLE Short name. Numbers in the BLE short name are being ignored. Example device long name Node 2, short name NDE2. After configuring the device as described the long name will show as Node 2 however the short name will simply be NDE (NDE_bbcc when displayed in apps to connect to).

**Comment by garthvh** [comment]
Issue is likely in one of these methods. BLE name is built automatically from SHORTNAME_LAST4OFMAC if the short name is something other than the last 4.  Short name is 5 bytes which is 4 characters max.

Some old 1.2 functionality remains in place in the CLI for short name 
--set-owner SET_OWNER Set device owner name Need to remove old automatic short name functionality that builds a short name from the owner string
 --set-owner-short SET_OWNER_SHORT Set device owner short name - Only supports 3 characters

**Comment by garthvh** [comment]
https://github.com/meshtastic/python/issues/364

**Comment by garthvh** [comment]
This is not just for the --configure method, any short name related method in the CLI truncates the name to 3 characters
