### ISSUE TITLE
Traceroute not working reliable

### ISSUE THREAD

**Issue by SR7673** [meshtastic/python#425]
On version 2.0.12, i'm getting unreliable traceroute results. Mostly it times out, rarely i'm getting a result.
It looks like it works more reliable on the RAK4631 than on the TBeam V1.1, don't ask me why...
Traceroute is an important function when building up meshes...

**Comment by GUVWAF** [comment]
Which firmware version are you using? There were a lot of radio level fixes lately, and using 2.1 (especially 2.1.2 for SX1262 radios) should give you better performance.

**Comment by GUVWAF** [comment]
Confirmed on Discourse that firmware version 2.1.2 makes this more reliable.
