### ISSUE TITLE
No more python2 at Debian Bookworn 

### ISSUE THREAD

**Issue by GrulClatu** [meshtastic/python#459]
Do you plan to develop a python3 version soon?

**Comment by rc14193** [comment]
Can you clarify what you're referring to? I'm new to the code but I checked the setup.py and some of the files and it seems like they're using python3. I'm also able to run the examples using 3.10 
![image](https://github.com/meshtastic/python/assets/62862738/183a5689-73d4-4500-af34-9dfa4c383a58)
