### ISSUE TITLE
mestastic 2.2.8 exe file virus problem ?

### ISSUE THREAD

**Issue by NickDolfin** [meshtastic/python#460]
Hi,

Deepguard blocked the execution of mestatic.exe.
Version 2.2.8

my older version 2.2.6 does not trigger my virus scanner.
Any idea's?

**Comment by jp-bennett** [comment]
https://www.virustotal.com/gui/file/46531837d5713d899884590929487eb6435872e4d841ec29672891dbec951c22/detection

It's probably a false positive, but that's not great.

**Comment by garthvh** [comment]
The stand alone windows installer has been removed from distribution.
