### ISSUE TITLE
Unable to update via pip - esptool version is ahead of supported version

### ISSUE THREAD

**Issue by kingoffoxes** [meshtastic/python#479]
Using Windows 22H2.

Getting the folllowing error. esptool version is ahead of supported version. 

meshtastic-flasher 1.0.106 requires esptool==3.3.1, but you have esptool 4.6.2 which is incompatible.

C:\Users\User>meshtastic --version
2.2.10

C:\Users\User>pip3 install --upgrade pytap2
Requirement already satisfied: pytap2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (2.3.0)

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

C:\Users\User>C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (23.3.1)
Collecting pip
  Downloading pip-23.3.2-py3-none-any.whl.metadata (3.5 kB)
Downloading pip-23.3.2-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 2.1/2.1 MB 12.2 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.3.1
    Uninstalling pip-23.3.1:
      Successfully uninstalled pip-23.3.1
Successfully installed pip-23.3.2

C:\Users\User>pip3 install --upgrade meshtastic
Requirement already satisfied: meshtastic in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (2.2.10)
Collecting meshtastic
  Downloading meshtastic-2.2.17-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: pyserial>=3.4 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from meshtastic) (3.5)
Requirement already satisfied: protobuf>=3.13.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from meshtastic) (3.19.1)
Requirement already satisfied: requests>=2.25.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from meshtastic) (2.27.0)
Requirement already satisfied: pypubsub>=4.0.3 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from meshtastic) (4.0.3)
Requirement already satisfied: dotmap>=1.3.14 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from meshtastic) (1.3.25)
Requirement already satisfied: pexpect>=4.6.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from meshtastic) (4.8.0)
Requirement already satisfied: pyqrcode>=1.2.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from meshtastic) (1.2.1)
Requirement already satisfied: tabulate>=0.8.9 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from meshtastic) (0.8.9)
Requirement already satisfied: timeago>=1.0.15 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from meshtastic) (1.0.15)
Requirement already satisfied: pyyaml in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from meshtastic) (6.0)
Requirement already satisfied: ptyprocess>=0.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pexpect>=4.6.0->meshtastic) (0.7.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.25.0->meshtastic) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.25.0->meshtastic) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.25.0->meshtastic) (2.0.9)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.25.0->meshtastic) (3.3)
Downloading meshtastic-2.2.17-py3-none-any.whl (86 kB)
   ---------------------------------------- 86.7/86.7 kB 2.5 MB/s eta 0:00:00
Installing collected packages: meshtastic
  Attempting uninstall: meshtastic
    Found existing installation: meshtastic 2.2.10
    Uninstalling meshtastic-2.2.10:
      Successfully uninstalled meshtastic-2.2.10
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
meshtastic-flasher 1.0.106 requires esptool==3.3.1, but you have esptool 4.6.2 which is incompatible.
Successfully installed meshtastic-2.2.17

C:\Users\User>meshtastic --version
2.2.10

C:\Users\User>

**Comment by caveman99** [comment]
Thats not an error. the Meshtastic CLI will run fine. Somehow you installed the (deprecated) desktop flasher in the past, that's the one thats causing the error. if you uninstall meshtastic-flasher the error will vanis.
