### ISSUE TITLE
Not sending requested config change over remote admin device

### ISSUE THREAD

**Issue by isaacbentley** [meshtastic/python#495]
**Description**
When using the standalone CLI  for Windows  and pip installed for Linux using the `--dest !<device ID>
` it's not setting the configuration as expected.

**Reproduction steps**

1. Download https://github.com/meshtastic/python/releases/download/2.2.22/meshtastic_windows.
2. Execute the downloaded file with the --dest parameter (via USB)
3. Results in executing the commands such as `--setlat` and `--setlon` successfully but it configures the local device, not the remote device as targeted in the `--dest` command. 

**Notes**
Verified that I'm able to remote configure remote devices via IOS & Andriod applications.

**Comment by isaacbentley** [comment]
Thank you for the quick response! I'll try to update the location by your suggestion and update this comment

**Comment by garthvh** [comment]
Remote location configuration is not available as it would allow nodes to change each other's location
