### ISSUE TITLE
Set remote node coordinates via admin channel

### ISSUE THREAD

**Issue by cascafico** [meshtastic/python#502]
device: Heltec V3
firmwareVersion: 2.2.23.5672e68

Sending latitude or longitude position to destination node, actually set only sender coordinates and reboots sender. Receiver coordinates unchanged.

ie:
```
meshtastic --dest '!da5c7d78' --setlat 46.4384
Connected to radio
Fixing latitude at 46.4384 degrees
Setting device position
```

**Comment by garthvh** [comment]
This is not supported intentionally. This would allow nodes to change each other's position

**Comment by cascafico** [comment]
I supposed it would work for remote node admin: on same channel I can change destination owner name.
