### ISSUE TITLE
Feature request: querying nodes for their firmware version

### ISSUE THREAD

**Issue by IZ1IVA** [meshtastic/python#519]
Hi,

is it possible to implement a mechanism to query a node in the mesh to retrieve its firmware version? I can see that as a way to speed up troubleshooting when breaking changes across versions are not expected but suspected, such as what we are currently experiencing between 2.2 and 2.3.

Due to its use case, it might not be necessary to implement this feature in the mobile apps; the Python CLI could instead be more fitting.

Cheers

**Comment by garthvh** [comment]
It is not available without an admin channel, firmware is part of the device metadata packet already.
