### ISSUE TITLE
Broken link in readme.txt

### ISSUE THREAD

**Issue by clwgh** [meshtastic/python#529]
Where: the standalone utility at https://github.com/meshtastic/python/releases

The file `readme.txt` includes the line

>See https://meshtastic.org/docs/software/python/python-standalone for more info.

This link is broken

>Page Not Found
We could not find what you were looking for.
Please contact the owner of the site that linked you to the original URL and let them know their link is broken.

**Comment by ianmcorvidae** [comment]
Thanks, appreciate the heads-up. I've updated the link to the appropriate spot in the docs (they've seen a bit of reorganization lately).

**Comment by clwgh** [comment]
You're very welcome, thanks.
