### ISSUE TITLE
Display more channel details with --info arguments

### ISSUE THREAD

**Issue by thebentern** [meshtastic/python#53]
It would be swell to see some of the channel details that we see over the serial logs, such as actual frequency, with the --info argument.
For more context:
https://meshtastic.discourse.group/t/antenna-improved-range/227/102?u=thebentern

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/antenna-improved-range/227/105

**Comment by mkinney** [comment]
@mc-hamster Is the freq exposed in protobufs? I don't see it.

**Comment by luzpaz** [comment]
Just checking the status of this ticket, is there something left to do here?

**Comment by garthvh** [comment]
These are details that are not part of the api
