### ISSUE TITLE
Link to Documentation deployement is offline / broken

### ISSUE THREAD

**Issue by Jorropo** [meshtastic/python#531]
The following links to the docs:
> [Documentation/API Reference](https://python.meshtastic.org/)

in [`README.md`](./README.md) and https://pypi.org/project/meshtastic/ page yields:
![image](https://github.com/meshtastic/python/assets/24391983/ae451e3a-b62d-4dd0-9f8a-72a8a0667fd9)

thx.

**Comment by Jorropo** [comment]
Someone in Discord mentioned:
> I think they got taken down just recently because they were really out of date, or something? Pending a rewrite? A code update? Don't remember sorry

Then this link should be removed, a stale link with `DEPLOYMENT_NOT_FOUND` looks very unintentional. :slightly_smiling_face:

**Comment by ianmcorvidae** [comment]
I've removed the link for now, thanks for the heads-up!

**Comment by VideoFX** [comment]
Where to find docs on the API?
