### ISSUE TITLE
--nodes does not return channel, shows N/A

### ISSUE THREAD

**Issue by joawib70** [meshtastic/python#562]
Using argument --nodes, I was expecting see the channel used to communicate with each node.
This information appears as N/A for all devices in the list.
![image](https://github.com/meshtastic/python/assets/40765037/1f61b595-f838-4b2c-b0c0-6357f7e66845)

**Comment by ianmcorvidae** [comment]
Good point, we should always know what channel it is. Protobufs don't distinguish between 0 and a missing value, so these were getting filled in with the missing-value text.
