### ISSUE TITLE
Enhancement: --request-environmental

### ISSUE THREAD

**Issue by joneyes** [meshtastic/python#596]
It is possible to request the following via CLI for a remote node:
--request-position (returns position co-ords & alt)
--request-telemetry (returns current device metrics)

Is it possible to add --request-environmental to query environmental metric data, when enabled?

**Comment by joneyes** [comment]
OK - I'll raise and enhancement request

**Comment by joneyes** [comment]
OK - I'll raise and enhancement request

**Comment by joneyes** [comment]
Firmware to support this has now been updated.

**Comment by ianmcorvidae** [comment]
Excellent, thanks for shepherding that. I'll try to get it implemented over here sometime soon, hopefully.

**Comment by joneyes** [comment]
Did you make any progress on this? - specifically looking for the power metrics telemetry

**Comment by ianmcorvidae** [comment]
I totally lost track of it, I'm sorry. I put together a PR to make this possible, which should go into the next release. I made it work by passing a second argument along with `--request-telemetry` to specify the subtype desired, rather than individual arguments for each type.
