### ISSUE TITLE
[BUG] Emoji character in node name screws up tabular formatting of --nodes

### ISSUE THREAD

**Issue by brad28b** [meshtastic/python#598]
See attached image. The node 'Highton Rooftop' is using an Emoji in their node name. It screws up the tabular formatting of the output for the --nodes argument, making it harder to parse, and visually messy.
![Screenshot 2024-06-17 151037](https://github.com/meshtastic/python/assets/70585927/301edabb-1dfd-4fd8-b90c-62a03b9a7d6f)

**Comment by ianmcorvidae** [comment]
This is a weakness of the underlying library, `tabulate`, but can be corrected by installing the library `wcwidth` (which is not included by default with `tabulate`.

If you run `pip install wcwidth` within the same environment you installed `meshtastic`, it should be corrected

**Comment by brad28b** [comment]
Thank you very much the very fast response. I can confirm your recommendation fixes it. Would it be worth adding wcwidth as a dependency?

**Comment by ianmcorvidae** [comment]
With #723 this should now be installed when meshtastic is installed as `meshtastic[cli]` (which as of recently also includes some other cosmetic sorts of dependencies, such as `print_color`). It won't be installed with a very basic install, especially so that library users don't need to install the wcwidth library.

**Comment by brad28b** [comment]
It still seems to be broken with the 👀 character, see attached. This is after a new install of meshtastic[cli], using Windows 11.

![Screenshot 2024-12-22 143612](https://github.com/user-attachments/assets/4514cc6a-627f-44ac-9c16-07fee67eb871)

**Comment by ianmcorvidae** [comment]
I think you may have tested before I formally cut the release that included this. Could you try updating again to CLI version 2.5.7, with `meshtastic[cli]`? That should install `wcwidth` and display this correctly.

**Comment by brad28b** [comment]
I just tried again, those googley eyes emoticon still seem to screw it up, but it works fine for all other emoticons. 

Confirm wcwidth was installed.
