### ISSUE TITLE
Switch from raw virtualenvs for building to Poetry

### ISSUE THREAD

**Issue by geeksville** [meshtastic/python#604]
[Poetry](https://python-poetry.org/) is a IMO very nice/modern/easy/repeatable python build/deployment/release tool.  It is pretty popular and I wish I had used it originally.   It also handles releasing to pypi, multiple build/execution flavors and replaces requirements.txt.

Underneath it is still virtualenv based, so any dev used to the current virtualenv workflows can still build/work that way if they wish.

I had chatted here with folks about a month ago and the idea seemed generally well received.  So I have a working version in my python [dev tree](https://github.com/geeksville/Meshtastic-python/tree/dev).

There are some remaining items:
* make sure all the existing CIish rules work
* update the dev docs to give basic "how to build using poetry" instructions.  Include a section on "how to make it look like the old virtualenv thing if that's your jam"
* clean up into an atomic PR

Making this issue for our discussion and so I can track my todo list.

**Comment by ianmcorvidae** [comment]
Looks like this didn't self-close itself so handling that now!
