### ISSUE TITLE
bump up the version of the nanopb tool to 0.4.8?

### ISSUE THREAD

**Issue by geeksville** [meshtastic/python#610]
Would ya'll be okay with that?  Then it would match the version being used in firmware.  0.4.8 has been the current version since 11/2023.

(a minor thing but then I'd just have one version in my /home/packages ;-)

**Comment by ianmcorvidae** [comment]
I'm always on team "if it doesn't break stuff, go for it", pretty much, haha. I imagine it works alright if firmware is using it, but if there's even any meaningful changes in the generated files we can make sure they're not an issue fairly easily I suspect.

**Comment by geeksville** [comment]
Ok Cool beans I'll test and send in a PR!

(Sent from a phone - please ignore typos)
