### ISSUE TITLE
Bluetooth device logging interface

### ISSUE THREAD

**Issue by thebentern** [meshtastic/python#614]
In firmware version 2.3.14, a new bluetooth characteristic `6c6fd238-78fa-436b-aacf-15c5be1ef2e2` was added to be a notify characteristic for serial style logs from the connected device when `bluetooth.device_logging_enabled` is true.

I've only implemented this on Apple clients so far:
![image](https://github.com/meshtastic/Meshtastic-Android/assets/9000580/241e9c3c-6188-41b0-a94e-a785960459a2)

I think it would be a neat feature to expose on Python as well, perhaps in a similar manner to --noproto, since they're the same logs essentially.

**Comment by ianmcorvidae** [comment]
@thebentern is this closed by #609 ? I'm being lazy about reading to be sure if there's any extra work we need to do there.

**Comment by thebentern** [comment]
Closed by #616
