### ISSUE TITLE
request  for settings via remote admin returns wrong info

### ISSUE THREAD

**Issue by zl3ag** [meshtastic/python#630]
Example 1:

# meshtastic --port /dev/ttyACM0 --dest '!25c2f43c' --get position
Connected to radio
Requesting current config from remote node (this can take a while).

serial:

Completed getting preferences

Example 2:

# meshtastic --port /dev/ttyACM0 --dest '!25c2f43c' --get network
Connected to radio
Requesting current config from remote node (this can take a while).

store_forward:

Completed getting preferences

**Comment by ianmcorvidae** [comment]
What version of the CLI are you running? This is an issue that came up at one point the other month, but was fixed then. There was some changes to related code recently though, so it could be a regression.

**Comment by zl3ag** [comment]
Upgraded to v2.3.13 just before experimenting with remote admin for the first time.

**Comment by ianmcorvidae** [comment]
Ah, yes, I see the issue. Same spot as before, unfortunately. I'll get a fix put in before the next release, which should hopefully be pretty soon.
