### ISSUE TITLE
Clean-up command line options --help

### ISSUE THREAD

**Issue by geeksville** [meshtastic/python#631]
We have a lot of command line options now.  I'd like to clean up their creation by grouping related options into option groups, so that --help can be a bit more readable.  cool?  If so I'll make and send a PR.

**Comment by ianmcorvidae** [comment]
I've done this! I'd be happy to see more organization if you've got ideas, so feel free to send a PR if you find some time & motivation, but I'll close the issue for now to clean up the issues list a bit.
