### ISSUE TITLE
configure does not survive PKI keys 

### ISSUE THREAD

**Issue by jhps** [meshtastic/python#678]
In 2.5 (65305af1840f720eb6e3f7aa0772aa0dd6f8c27e), a configuration that has privateKey, publicKey, or adminKeys causes the cli to exit with:
`Aborting due to: expected bytes, str found`

It seems that MessageToDict() converts bytes to base64 strings that are saved in the config yaml but when these are are later loaded into a config to be sent a setattr() of a string to a bytes field causes an exception.

**Comment by contra-bit** [comment]
I'd like to mention that also the Python CLI has an issue with serializing public keys, which always converts them to a string or bytes, regardless of the input format.  This should be fixed to ensure consistent behavior.
   
 Fixes:
 - [ ] Fix the Python CLI issue with serializing public keys.
    
 All of these examples produce the same error. 
 ```
 meshtastic --set security.is_managed true --set security.admin_key b'XXXXXXXXXXXXXXXXXXXXXXXXXX' --set security.admin_channel_enabled true
 meshtastic --set security.is_managed true --set security.admin_key XXXXXXXXXXXXXXXXXXXXXXXXXX --set security.admin_channel_enabled true
 meshtastic --set security.is_managed true --set security.admin_key 'XXXXXXXXXXXXXXXXXXXXXXXXXX' --set security.admin_channel_enabled true
 ```
 In the example with: b'XXXXXXXXXXXXXXXXXXXXXXXXXX' the it tries to add the b to the bytes

The fix should allow document how to add multiple admin keys as per https://github.com/meshtastic/web/issues/315
