### ISSUE TITLE
No option to configure static IP due lack of attributes

### ISSUE THREAD

**Issue by D4rk4** [meshtastic/python#700]
By the [source code](https://github.com/meshtastic/firmware/blob/3f1c86f9535279fd17eaaab6e10a06f09915b7e4/src/mesh/eth/ethClient.cpp#L134) settings must be

`meshtastic --set network.ipv4_config.ip 1684302082 --set network.ipv4_config.dns 168430090 --set config.network.ipv4_config.gateway 1684302081 --set config.network.ipv4_config.subnet 4294967040
`

But some of them were rejected by meshtastic Python:

> LocalConfig and LocalModuleConfig do not have attribute config.network.ipv4_config.subnet.
> LocalConfig and LocalModuleConfig do not have attribute config.network.ipv4_config.gateway.

**Comment by ianmcorvidae** [comment]
the ones with `config` should not have that prefix; all four should start with `network.ipv4_config`
