### ISSUE TITLE
Fresh install of 2.5.6 breaks dependencies

### ISSUE THREAD

**Issue by battlehax** [meshtastic/python#717]
Something that changed in the dependencies today has broken fresh installs of the library's cli tool. You can see this by creating a new venv, entering it, and installing meshtastic, then running any command that talks to a device via serial or tcp.

`$ meshtastic --info`
Traceback (most recent call last):
  File "/home/skot/venv/bin/meshtastic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/skot/venv/lib/python3.11/site-packages/meshtastic/__main__.py", line 1935, in main
    common()
  File "/home/skot/venv/lib/python3.11/site-packages/meshtastic/__main__.py", line 1211, in common
    client = meshtastic.serial_interface.SerialInterface(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'meshtastic' has no attribute 'serial_interface'. Did you mean: 'mesh_interface'?

This can be resolved by running `pip install meshtastic==2.5.5` followed by `pip install --upgrade meshtastic`

**Comment by ianmcorvidae** [comment]
Thanks! Fixed with https://github.com/meshtastic/python/commit/d66b8fa9dde469fd5e987c694e6cec91ecb98210
